import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-bright': '#102a5b',
        'on-error': '#490006',
        'primary-container': '#0d60d2',
        'on-background': '#dde5ff',
        'tertiary-container': '#fdb330',
        'primary': '#afc6ff',
        'tertiary-fixed-dim': '#eda521',
        'surface-container-lowest': '#000000',
        'secondary-fixed': '#6bff8f',
        'outline': '#5f74a9',
        'surface-tint': '#afc6ff',
        'surface-dim': '#030d24',
        'on-tertiary-container': '#543700',
        'secondary-dim': '#38d36a',
        'secondary-fixed-dim': '#5bf083',
        'secondary': '#22c55e',
        'on-tertiary-fixed-variant': '#5f3f00',
        'surface-container-low': '#021231',
        'on-secondary': '#004b1e',
        'surface-container-high': '#071e46',
        'background': '#0b0f19',
        'inverse-on-surface': '#4b556f',
        'error-container': '#871f21',
        'on-secondary-fixed': '#004a1d',
        'outline-variant': '#304778',
        'surface': '#131a2b',
        'error': '#f04b4b',
        'surface-container': '#04183c',
        'on-surface-variant': '#a8b3c7',
        'on-primary-fixed': '#000000',
        'surface-container-highest': '#072354',
        'error-dim': '#c54d4a',
        'on-primary-container': '#ffffff',
        'on-secondary-container': '#41da70',
        'primary-dim': '#4f8cff',
        'on-primary': '#003c8b',
        'on-tertiary-fixed': '#382400',
        'on-tertiary': '#603f00',
        'tertiary-dim': '#eda521',
        'secondary-container': '#00461b',
        'on-surface': '#e7ebf3',
        'tertiary': '#f0a824',
        'on-secondary-fixed-variant': '#006a2d',
        'primary-fixed': '#4a88fb',
        'on-error-container': '#ff9993',
        'inverse-primary': '#005ac8',
        'tertiary-fixed': '#fdb330',
        'surface-variant': '#232d45',
        'on-primary-fixed-variant': '#001336',
        'inverse-surface': '#faf8ff',
        'primary-fixed-dim': '#3a7bed',
        // Semantic aliases used in screen3
        'semantic-green': '#22c55e',
        'semantic-yellow': '#f0a824',
        'semantic-red': '#f04b4b',
        // screen3 explicit vars
        'page-bg': '#0b0f19',
        'card-bg': '#131a2b',
        'border-color': '#232d45',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'card-padding': '24px',
        'row-height-compact': '44px',
        'section-gap': '48px',
        'card-gap': '16px',
      },
      fontFamily: {
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'data-number': ['Inter', 'sans-serif'],
        'label-md': ['Space Grotesk', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'data-number': ['16px', { lineHeight: '1', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
      animation: {
        'fadeIn': 'fadeIn 0.2s ease-out',
      },
    },
  },
  plugins: [],
}

export default config
